### ISSUE TITLE
error E0603

### ISSUE THREAD

**Issue by Zuzuk-null** [Marwes/serde_state#6]
error[E0603]: module `private` is private
   --> /home/daniil/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_state-0.4.7/src/private/de.rs:16:16
    |
16  | pub use serde::private::de ::InPlaceSeed;
    |                ^^^^^^^ private module
    |
note: the module `private` is defined here
   --> /home/daniil/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.120/src/lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Marwes** [comment]
Uploaded a version with this fixed (and updated with all the newer serde additions)
