### ISSUE TITLE
Support for `SerializeMap`

### ISSUE THREAD

**Issue by segeljakt** [Marwes/serde_state#9]
Hi, thanks for the great crate @Marwes. I'm wondering, is it possible to use `serde::ser::SerializeMap` (and other data types) with `serde_state`?

When I try to use it, `serde` complains that the type does not implement `Serialize` (it implements `SerializeState`):

<img width="750" alt="image" src="https://user-images.githubusercontent.com/15143039/165538126-33a0c272-045b-494d-9dbf-5f21864fd196.png">

**Comment by Marwes** [comment]
Assuming you have the state accessible you can use https://docs.rs/serde_state/0.4.8/serde_state/ser/struct.Seeded.html to get a value which implements `Serialize`

**Comment by segeljakt** [comment]
Oh, perfect! Thanks 👍
